<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Python Programming</title>
    <link rel="stylesheet" type="text/css" href="my.css">
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
</head>


<pre>
<code class="inline_code">
def find_largest(arr):
    #your code here!
    return 0
 
 #Unit Tests
 
def asserter(test_case, exp, func, *args):
    try:
        ret = func(*args)
        if ret == exp:
            print("Test Case " + str(test_case) + " SUCCESS!")
        else:
           print("Test Case " + str(test_case) + " FAILED. We expected: " + str(exp) + " but you returned " + str(ret))
     except Exception as e:
        print("Test Case " + str(test_case) + f" had an exception: {type(e).__name__}: {e}")
 
asserter(1, 3, find_largest, [0,1,2,3])
asserter(2, 2, find_largest, [2,1])
asserter(3, 1, find_largest, [1])
asserter(4, "error", find_largest, [])
asserter(5, 0, find_largest, [0,0,0,0])
asserter(6, 1, find_largest, [-299, -500, 1, -13])
asserter(7, 16, find_largest, [16,15,14,13])
asserter(8, 11, find_largest, [1,2,5,4,7,4,8,2,4,5,7,4,7,9,11,4])
</code>
</pre>