<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Python Programming</title>
    <link rel="stylesheet" type="text/css" href="my.css">
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
</head>


<pre>
    <code class="inline_code">
def swap(arr, num1, num2):
        #your code here



asserter(test_case, exp, func, *args):
try:
    ret = func(*args)
    if ret == exp:
       print("Test Case " + str(test_case) + " SUCCESS!")
    else:
      print("Test Case " + str(test_case) + " FAILED. We expected: " + str(exp) + " but you returned " + str(ret))
except Exception as e:
    print("Test Case " + str(test_case) + f" had an exception: {type(e).__name__}: {e}")

asrter(1, [1,3,2], swap, [1,2,3], 2, 3)
assrter(2, [2,1], swap, [1,2], 1, 2)
assrter(3, [7,2,3,4,5,6,1], swap, [1,2,3,4,5,6,7], 1, 7)
assrter(4, [1,2,5,4,3], swap, [1,2,3,4,5], 3, 5)
assrter(5, [1,9,2,7], swap, [1,7,2,9], 7, 9)
    
</code>
</pre>